[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect all requests to /index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

